### ISSUE TITLE
Order bys en consultas.

### ISSUE THREAD

**Issue by mongui** [UDA-EJIE/udaPlugin#2]
Pongamos que tenemos una columna de una tabla rup_table en presentación que se llama Nombre completo. Esta se compone de la suma de los campos T01APELLIDO1 + " " + T01APELLIDO2 + ", " + T01NOMBRE.
Para poder realizar una ordenación ascendente, en el Service se nos hace necesario añadirle al método correspondiente (normalmente al filter) lo siguiente:

`
if (jqGridRequestDto.getSidx() != null && jqGridRequestDto.getSord().equalsIgnoreCase("ASC") && jqGridRequestDto.getSidx().equals("nombreCompleto")) {
	jqGridRequestDto.setSidx("T01APELLIDO1, T01APELLIDO2, T01NOMBRE");
}
`

Para ordenarlo de forma descendente hay que indicarle 

`
if (jqGridRequestDto.getSidx() != null && jqGridRequestDto.getSord().equalsIgnoreCase("DESC")
 && jqGridRequestDto.getSidx().equals("nombreCompleto")) {
	jqGridRequestDto.setSidx("T01APELLIDO1 DESC, T01APELLIDO2 DESC, T01NOMBRE");
}
`

La nueva versión de UDA incluye un sistema de filtrado de campos ORDER_BY_WHITE_LIST en el que se indican cuáles están permitidos al realizar una búsqueda y que se utiliza para temas de paginado de tablas.

Para esta columna compuesta de tres campos es necesario añadir al ORDER_BY_WHITE_LIST los campos { "T01APELLIDO1 DESC", "T01APELLIDO2 DESC" } ya que el método JQGridManager.getPaginationQuery que aplica el filtrado de campos permitidos no elimina el ordenador DESC.

Tanto el sistema de ordenación ` jqGridRequestDto.setSidx("T01APELLIDO1 DESC, T01APELLIDO2 DESC, T01NOMBRE"); ` como el de paginación JQGridManager.getPaginationQuery deberían mejorarse en las siguientes versiones para que se pueda escribir un código más limpio.

**Comment by xaabi6** [comment]
Se cierra la issue por inactividad y porque el código al que se hace referencia ya no está presente en el proyecto.

Si fuese necesario, reabrir la issue por favor.
