### ISSUE TITLE
Error al realizar un borrado múltiple

### ISSUE THREAD

**Issue by tiagoes92** [UDA-EJIE/udaPlugin#7]
Hola, he encontrado el siguiente error cuando se hace un borrado múltiple.

Se ha creado una tabla normal con los botones de añadir y borrar, y selección múltiple. Cuando se seleccionan todos los registros y se da en la opción de borrar, no está pasando el filtraje del filtro al método de borrar del **controller**.

Este es el filtro que tiene la tabla:
![image](https://user-images.githubusercontent.com/50843438/106883949-f8ee3400-66e0-11eb-9d2c-47563d76b95f.png)

Marcamos todos:
![image](https://user-images.githubusercontent.com/50843438/106884690-eb857980-66e1-11eb-8b61-a4fd10a7b7d5.png)

Eliminamos los registros:
![image](https://user-images.githubusercontent.com/50843438/106883987-099eaa00-66e1-11eb-94a1-eb04414799fb.png)

Si nos fijamos en la llamada sólo se están mandando los datos del **TableRequestDto**, no tiene el filtro
![image](https://user-images.githubusercontent.com/50843438/106884224-4c608200-66e1-11eb-83f4-c891b5a960fd.png)

Y en el **controller**, el método que crea el generador de código sólo tiene el objeto **TableRequestDto**, y además se genera sin **@RequestJsonBody**
![image](https://user-images.githubusercontent.com/50843438/106884265-5bdfcb00-66e1-11eb-8cc4-1900d7716d50.png)

Un saludo.

**Comment by xaabi6** [comment]
Gracias por reportarlo, lo añadimos a la lista de tareas de cara a tenerlo corregido en la próxima liberación de versión.

**Comment by xaabi6** [comment]
Ya están todos los cambios necesarios aplicados, en la siguiente versión de UDA estará todo disponible para su uso.

Resumiendo un poco el trabajo realizado, ahora la parte front-end de UDA se encarga de enviar siempre el filtro cuando se trata de una petición de eliminación múltiple. Los cambios en controladores, servicios y DAOs existentes hay que hacerlos de manera manual porque, aunque han sido incluidos en las plantillas, estas sólo sirven para nuevas generaciones, dicho esto, os dejo unos ejemplos que tendréis que adaptar un poco a vuestras necesidades pero que os pueden servir:

- **Controller**: 
```java
/**
 * Removes multiple rows from the Usuario table.
 *  
 * @param filterUsuario Bean que contiene los parámetros de filtrado a emplear.
 * @param tableRequestDto Dto que contiene los parámetros de configuración propios del RUP_TABLE a aplicar en la búsqueda.
 *
 * @return List<String> Lista de los identificadores de los registros eliminados. 
 */
@RequestMapping(value = "/deleteAll", method = RequestMethod.POST)
@ResponseStatus(value = HttpStatus.OK)
public @ResponseBody List<String> removeMultiple(
		@RequestJsonBody(param="filter") Usuario filterUsuario,
		@RequestJsonBody TableRequestDto tableRequestDto) {
        this.usuarioService.removeMultiple(filterUsuario, tableRequestDto, false);
	return tableRequestDto.getMultiselection().getSelectedIds();
}
```

- **Service**:
```java
/**
 * Removes multiple rows from the Usuario table.
 *
 * @param filterUsuario Usuario
 * @param tableRequestDto TableRequestDto
 * @param startsWith Boolean
 */	
void removeMultiple(Usuario filterUsuario, TableRequestDto tableRequestDto, Boolean startsWith);
```

- **ServiceImpl**:
```java
/**
 * Removes multiple rows from the Usuario table.
 *
 * @param filterUsuario Usuario
 * @param tableRequestDto TableRequestDto
 * @param startsWith Boolean
 */		
@Transactional(rollbackFor = Throwable.class)
public void removeMultiple(Usuario filterUsuario, TableRequestDto tableRequestDto, Boolean startsWith){
	this.usuarioDao.removeMultiple(filterUsuario, tableRequestDto, startsWith);
}
```

- **DAO**:
```java
/**
 * Removes multiple rows from the Usuario table.
 *
 * @param filterUsuario Usuario
 * @param tableRequestDto TableRequestDto
 * @param startsWith Boolean
 */	
void removeMultiple(Usuario filterUsuario, TableRequestDto tableRequestDto, Boolean startsWith);
```

- **DAOImpl**:
```java
/**
 * Removes multiple rows from the Usuario table.
 *
 * @param filterUsuario Usuario
 * @param tableRequestDto TableRequestDto
 * @param startsWith Boolean
 */
@Override
public void removeMultiple(Usuario filterUsuario, TableRequestDto tableRequestDto, Boolean startsWith) {
	// Like clause and params
	Map<String, Object> mapWhereLike = this.getWhereLikeMap(filterUsuario, startsWith);
		
	// Delete query
	StringBuilder sbRemoveMultipleSQL = TableManager.getRemoveMultipleQuery(mapWhereLike, tableRequestDto, Usuario.class, "USUARIO", "t1", new String[]{"ID"});
		
	// Params list. Includes needed params for like and IN/NOT IN clauses
	List<Object> params = (List<Object>) mapWhereLike.get("params");
	params.addAll(tableRequestDto.getMultiselection().getSelectedIds());
		
	this.jdbcTemplate.update(sbRemoveMultipleSQL.toString(), params.toArray());
}
```

Finalmente, los DAOs harán una llamada al método ```getRemoveMultipleQuery``` de la clase ```TableManager``` que pertenece a la librería X38 y esta, que será la que se encargue de generar una consulta incluyendo el filtro, también ha recibido los cambios necesarios.
