### ISSUE TITLE
compatibilidad con linux

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaPlugin#8]
¿Existe alguna versión con compatibilidad para linux?
Intento ejecutar el plugin pero da errores para crear una carpeta /config: ¿se puede mejorar para que sea en la ubicación del HOME?
Al subsanar esto, la tarea ant que resuelve las librerias intenta ejecutar el archivo mvn.bat el cual obviamente no es funcional en linux...

Gracias por toda la colaboración que puedan prestar

Jon Ander Aguinaco

**Comment by xaabi6** [comment]
Aupa @JONAGUIPER, aunque el plugin puede ejecutarse en entornos Linux, todo lo que dices tiene sentido, pero no teníamos constancia de que estuviese fallando porque la inmensa mayoría de usuarios lo ejecutan en Windows.

Dicho esto, agradecemos que lo hayas reportado para que podamos corregirlo, te avisaremos por aquí cuando esté solventado.

Un saludo y gracias.

**Comment by JONAGUIPER** [comment]
Gracias por responder!! la tarea ANT pude resolverla modificando el template correspondiente eliminando el .bat
Ahora viendo el plugin me di cuenta que el problema es que esa ubicación donde se guardan los ficheros de configuración de la app esta almacenado en una Constante. Plantearía dejar ese Path como un parámetro que se solicite al crear la app, tal y como se hace para almacenar la misma app que se va a crear.

En otro orden de ideas. He intentado crear un eclipse con todos los plugins necesarios para hacerlo funcionar en linux, sin mucho éxito, logro instalar OEPE pero en el momento que instalo la versión de hibernate tools me solicita hacer update del propio eclipse y ya ahí empiezan los problemas.

Si existe alguna manera de hacerlo me podrias indicar ya que en la documentación lo que sale es para una versión de OEPE, hibernate tools y etc obsoletas o diferentes a los que se encuentran instalados en el eclipse que ponen a disposición para windows.

Muchas gracias y mis disculpas por tanta turra
PD: lo del eclipse no se si meterlo en otro hilo o issue, me comentas

**Comment by xaabi6** [comment]
He estado dándole una vuelta a esto y creo tener todo más o menos atado, déjame darle un repaso más a fondo y generar una versión de prueba del plugin y plantillas para que puedas probarlo por nosotros si no es menester.

Respecto a Eclipse, tenemos pensadas cosas para desligarle el plugin y así cada uno pueda desarrollar con el IDE de su elección, pero por el momento, toca seguir con la combinación actual. Te cuento esto porque el plugin nos obliga a usar ciertas dependencias desactualizadas y por eso al actualizar Eclipse, comienzan los problemas. Hace unos meses estuvimos tratando bastante este tema, y aunque conseguimos hacerlo funcionar en la última versión estable de Eclipse, daba demasiados errores que ralentizaban la generación de aplicaciones y decidimos volver a lo estable, aunque estuviese ya obsoleto...

Si no te corre mucha prisa tener un Eclipse funcionando sobre Linux, dame un tiempo a que monte un entorno en Debian bullseye y ya me encargo yo de ello.

De turra nada, que Linux también existe 😄, y por la issue no te preocupes, podemos tratarlo por aquí porque no tenemos un repositorio dedicado a Eclipse.

Un saludo

Edito: plantillas y plugin listos para probar, aquí te dejo los enlaces:
- [Plugin v5.1.0-beta1](https://github.com/UDA-EJIE/udaPlugin/releases/tag/v5.1.0-beta1)
- [Plantillas v5.1.0-beta1](https://github.com/UDA-EJIE/udaTemplates/releases/tag/v5.1.0-beta1)

**Comment by xaabi6** [comment]
@JONAGUIPER, ¿pudiste probar el plugin y las plantillas que adjunté en el mensaje anterior?

**Comment by JONAGUIPER** [comment]
No había leído el mensaje disculpa pero mañana mismo lo pruebo

**Comment by JONAGUIPER** [comment]
Hola @xaabi6 he probado instalarlo sin instalar el hibernate tools y el plugin no se me muestra en ningún sitio dentro del eclipse :(
el problema principal que creo que tengo es que no se la versión de hibernate tools que debo instalar sin que me solicite descargar dependencias actuales que luego me obligan a ejecutar el eclipse con un jdk superior...
Podrías indicarme, si es posible, cuales son los plugins necesarios y sus versiones, que debo instalar antes UDA? 
yo estoy instalando OEPE e hibernate tools y después UDA

**Comment by xaabi6** [comment]
La versión de Hibernate Tools a usar es la **5.4.7.v20200224-1552** y la de Oracle WebLogic Server Tools la **17.3.0.201903121357**.

El procedimiento a seguir sería algo así:

1. Descargar versión 2020-03 (4.15.0) de [Eclipse IDE for Enterprise Java Developers](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-03/R/eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz).
2. Instalar Oracle WebLogic Server Tools del [repositorio de Oracle](https://download.oracle.com/otn_software/oepe/12.2.1.9/photon/repository/).
3. Instalar Hibernate Tools del [repositorio de JBoss](https://download.jboss.org/jbosstools/photon/stable/composite/4.14.0).
4. Instalar [plugin de UDA](https://github.com/UDA-EJIE/udaPlugin/releases).

También es importante mencionar que no debes actualizar Eclipse ni sus dependencias en ningún momento, porque de lo contrario, comenzarán a fallar cosas.

Y con esto ya deberías tenerlo funcionando, pruébalo y me comentas.

**Comment by JONAGUIPER** [comment]
Intento esto que me dices pero acabo de hacer funcionar todo en un eclipse 2022 y veo que colocaron la opción de agregar el path para los config y los datos: espectacular!!! muchas gracias
Voy a intentar crear un eclipse tal como dices y me dejo esta...
me invente un git para crear eclipses con las diferentes variantes para ver cual termina siendo la ganadora...
Muchísimas gracias... en breve te doy resultados de esta incursión a ver si logro que no se me actualice el eclipse que como te digo al instalar el hibernate me obliga si o si a actualizar paquetes

**Comment by xaabi6** [comment]
En un Eclipse de 2022 (no recuerdo cuál exactamente) lo conseguimos hacer funcionar, pero al generar una aplicación, el plugin lanzaba muchísimos errores (a cuenta de las Oracle Weblogic Server Tools que están desfasadas), eso sí, sorprendentemente, lo que es generar, generaba bien.

Si finalmente consigues hacerlo funcionar, te agradeceríamos mucho que nos los comentases por aquí para intentar replicarlo 😄

**Comment by xaabi6** [comment]
Por cierto, para el problema que comentas de que se te actualizan sí o sí los paquetes cuando instalas las **Hibernate Tools**, ¿has desmarcado la casilla _Contact all update sites during install to find required software_?, no sería la primera vez que me da problemas...

![hibernate_tools-install](https://user-images.githubusercontent.com/22637294/201061895-40eeed82-9326-4059-98d4-5ea8c96fba17.png)

**Comment by JONAGUIPER** [comment]
Pues esa opción no la había manejado nunca... lo intentare así a ver.
SI claro que te puedo pasar la versión que hice, dime como y te lo paso en cuanto termine esta prueba...

**Comment by JONAGUIPER** [comment]
Aqui le tienes por una semana
https://we.tl/t-TyEO15s9Mj
la dirección de la jdk en el eclipse.ini está modificada le meti la 11 y esto esta hecho en Ubuntu

**Comment by xaabi6** [comment]
Descargado, ¡gracias!

¿Has podido probar lo que te comenté en mi último mensaje?, creo que solventará el problema que comentabas.

**Comment by JONAGUIPER** [comment]
estoy en el segundo intento que creo que cuando instale oepe no lo marque y me estaba dando errores

**Comment by JONAGUIPER** [comment]
tengo la versión con 2020-03 en linux con la beta que me pasaste
https://we.tl/t-ncKO6mxS7a
Ha sido un éxito a la primera si mantenía ese check deshabilitado sin eso no lo hubiese logrado
los demás plugin entiendo que seran iguales?... sonar, svn , etc...?

**Comment by xaabi6** [comment]
Efectivamente, instala todos de la misma manera, de lo contrario, volverán los problemas.

**Comment by JONAGUIPER** [comment]
cuando pruebes las versiones que te mandé me comentas a ver si te tiran y si la 2022 funciona como debería me avisas para empezar a usarla a saco...
Muchísimas gracias por el soporte

**Comment by xaabi6** [comment]
De acuerdo, puede que tarde un tiempo en probarla, así que de mientras te recomendaría usar la **2020-03 (4.15.0)** que sabemos que funciona bien. Ahora bien, en la 2022 puedes comprobar fácilmente si funciona correctamente o no, simplemente prueba a generar una aplicación y comprueba que el proceso no sea muy lento, además, también conviene vigilar el log de errores de Eclipse.

Por el momento, voy a cerrar la issue porque el plugin ya es compatible con entornos Linux, gracias por tu tiempo 👍
