### ISSUE TITLE
Problemas con los mantenimientos

### ISSUE THREAD

**Issue by sergeisg** [UDA-EJIE/udaPlugin#9]
Hola. 
Estamos teniendo problemas con los mantenimientos que genera UDA. 

### Error 1 
Causado al intentar editar un registro de la tabla sobre la que se hace el mantenimiento. 
![Screenshot_57](https://user-images.githubusercontent.com/91953689/206218109-6581bd18-9651-44ec-aef3-8c5d13132386.jpg)
![Screenshot_56](https://user-images.githubusercontent.com/91953689/206218153-264f5638-1ea3-4ecc-a6b0-eb07743ef710.jpg)

El servidor devuelve un código 406 y la siguiente respuesta en la consola del navegador: 

> _JSON parse error: (was org.hdiv.filter.ValidationErrorException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was org.hdiv.filter.ValidationErrorException) (through reference chain: com.ejie.ad97a.model.Perfil["idPerfil"])_

Se ha identificado la anotación de Hdiv de la línea 34 en el modelo como causa de la excepción. Esta anotación se genera para todos los atributos ID de todos los modelos generados por UDA.
![Screenshot_54](https://user-images.githubusercontent.com/91953689/206215605-c55a395e-38b5-468e-ba89-1c59a54a108f.jpg)
Al ser una anotación de Hdiv, entiendo que está ahí por razones de seguridad, con lo que simplemente quitarla no es una solución.

### Error 2
Causado al borrar o editar un registro de la tabla sobre la que se hace el mantenimiento. También al añadir un registro que incluye datos generados por el sistema. 
Ejemplo: añadir a uno de los campos del registro una fecha de creación generada por el sistema, además de los valores introducidos por el usuario. 

En cualquiera de los tres casos, el servidor devuelve un código 406 y la siguiente respuesta en la consola del navegador: 

> _(was org.hdiv.filter.ValidationErrorException) (through reference chain: com.ejie.x38.dto.TableRequestDto["multiselection"]->com.ejie.x38.dto.TableRequestDto$Multiselection["selectedIds"])_

Al borrar un registro, no desaparece de la lista hasta refrescar la página.
Al editar un registro, aparece modificado en la lista, pero no se reordena la tabla en función del nuevo valor introducido.
Al añadir un registro, aparece en la tabla sin los valores generados por el sistema. 

En ninguno de los casos se obtienen trazas de error en la consola del backend. El error se produce en el método "filter" del controlador generado.
![Screenshot_59](https://user-images.githubusercontent.com/91953689/206226756-7c7a77bf-b56d-4cef-b162-0499a2a639c4.jpg)
El método "filter" si funciona correctamente al recargar la página, obteniendo todos los datos de las tablas, o a la hora de utilizar el formulario de filtrado generado. 

--------------------------
Gracias por su ayuda.
Un saludo.

**Comment by joxepo666** [comment]
Hola:

Tras seguir investigando el error, hemos descubierto que el error 2 que comenta Sergei, se produce siempre que se hace un "filter" de la tabla cuando hay elementos seleccionados en la misma. Si deseleccionas los elementos, ya sea por interfaz o programáticamente, el "filter" se hace correctamente.

Un saludo.

**Comment by xaabi6** [comment]
Aupa @sergeisg y @joxepo666, ¿podéis hacernos llegar la aplicación generada para que podamos echarle un vistazo? Gracias.

**Comment by joxepo666** [comment]
Aupa!

Xabi, te he dado acceso al repositorio privado donde está la aplicación.

Muchas gracias.

**Comment by xaabi6** [comment]
Perfecto Iraitz, en cuanto podamos le echamos un vistazo y os decimos algo.

**Comment by xaabi6** [comment]
@joxepo666, ¿puedes subir el proyecto de properties al repositorio por favor? Si es exactamente igual al que genera el plugin, puedo generarme uno sin problema.

**Comment by sergeisg** [comment]
@xaabi6 Es exactamente igual al que genera el plugin.

**Comment by xaabi6** [comment]
Aplicación desplegada, pero algo me dice que no tenéis la tabla o vista necesaria generada en la base de datos de desarrollo, ¿podéis generarla para que pueda probarlo?

**Comment by xaabi6** [comment]
Acabo de generarme una aplicación desde cero con el plugin (v5.1.0) y no consigo reproducir ninguno de los problemas que comentáis (tampoco en la x21a). Actualizar vuestra aplicación a la última versión liberada y probad a ver si sigue o no habiendo errores.

Otra posibilidad es que tengáis mal configurado el entorno, por ejemplo, ¿os carga el servidor la licencia de Hdiv cuando lo arrancáis?

**Comment by JONAGUIPER** [comment]
Hola @xaabi6 efectivamente tenemos un error en consola que nos dice que la licencia a expirado.
Investicando un poco en el manual que se subio hace un mes para WL12 aparece una linea en el start_weblogic.cmd que llama a un setHDIV.cmd cuestion que no tenemos.
buscamos en una documentación donde nos dice que hay un zip para descargar en esta url: http://www.otc.ejides.eus/hdiv a la cual no accedemos ni con VPN activa, por lo tanto no sabemos de que árbol ahorcarnos jajaja.
¿Sabrias y podrías redirigirnos a la documentación que indique como instalar este agente correctamente? 

Muchisismas  gracias

**Comment by xaabi6** [comment]
Aupa @JONAGUIPER.

Vale, si no tenéis la licencia, ya me empieza a cuadrar todo. No recuerdo exactamente en qué punto de la documentación está esa URL, pero por favor indicármelo para que pueda corregirlo porque el dominio es incorrecto, la dirección buena es [esta](http://www.otc.ejiedes.eus/hdiv/) y con la VPN deberíais de ser capaces de acceder.

Otra nota, como tenéis acceso por VPN a EJIE, descargaos el zip que se llama **Dev.Toolbar.Ejie(2.8.27)**.

Una vez hecho esto, descomprimid el archivo y ubicar su contenido donde mejor os parezca, después, tenéis que llamar desde _startWebLogic_ a _setHdiv_ (al igual que se hace en el documento de instalación).

Si os surge alguna duda más, solo tenéis que decirlo 👍

**Comment by JONAGUIPER** [comment]
Ya Xabi hemos hilado el telar y resuelto el tema era eso que no teniamos puesto el hdiv correctamente, pero sugerencia:
en el documento de instalacion de un entorno local no existe ninguna mención a este apartado, me di cuenta porque en el startweblogic.cmd de ejemplo que esta ahi si que llama el setHdiv y por ahí fui tirando hasta lograrlo... ¿no sería buena idea comentarlo ahí para cuando se instala con esas indicaciones no de guerra?

**Comment by xaabi6** [comment]
Tengo que revisar a ver si está en algún documento del portal del desarrollador, no obstante, aunque lo esté, deberíamos de mencionarlo para que no os volváis locos con esto, así que gracias por la sugerencia y disculpadnos por las molestias ocasionadas 😄

Entiendo entonces que ya os funciona correctamente, ¿verdad?

**Comment by JONAGUIPER** [comment]
Todo correcto xabi ya anda...
No problem para eso estamos para darnos una mano cuando se pueda.
Dato curioso: al habilitar el HDIV nos da error la app con otra cosa de spring y estamos probando aumentar la memoria de la JVM y parece que se subsanan los problemas...
Hoy lo estamos probando y te lo confirmamos el lunes pero dato para tener en cuenta...
Los datos que colocamos ahora son: WLS_MEM_ARGS_64BIT=-Xms512m -Xmx1024m en el setDomainEnv.cmd

**Comment by xaabi6** [comment]
Perfecto, confírmame cuando lo tengáis claro, de momento, voy a probarlo yo también a ver si mejora el rendimiento de WebLogic.

Por si os sirve de algo, en su momento incluí la variable **USER_MEM_ARGS** a mi _startWebLogic_, pero a mis ojos, no sirvió de mucho.

**Comment by xaabi6** [comment]
@JONAGUIPER, ¿os terminó el aumento de memoria por solventar los problemas con Spring?

**Comment by JONAGUIPER** [comment]
No Macho no funcionó

**Comment by xaabi6** [comment]
¿Qué problema os da exactamente?

**Comment by JONAGUIPER** [comment]
Hola xabi este es el error:
<20-dic-2022 17H17' CET> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 132; schema_reference: fallo al leer el documento de esquema 'spring-beans-4.3.xsd' porque no se permite el acceso 'http' debido a una restricci�n definida por la propiedad accessExternalSchema. :org.xml.sax.SAXParseException:schema_reference: fallo al leer el documento de esquema 'spring-beans-4.3.xsd' porque no se permite el acceso 'http' debido a una restricci�n definida por la propiedad accessExternalSchema. 
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	Truncated. see log file for complete stacktrace

esto pasa cuando haces publish y no despliega la app lo que obliga a reiniciar el weblogic

**Comment by xaabi6** [comment]
Entiendo, le echaremos un vistazo a ver qué vemos.

**Comment by xaabi6** [comment]
He estado revisando el problema que me comentaste @JONAGUIPER.

La propiedad `accessExternalSchema` fue añadida en Java 1.7 y sirve para limitar el acceso a esquemas externos, nada más y nada menos que eso. Se ve que por defecto, viene limitado y no permite el acceso por el protocolo http, lo que provoca el fallo.

Esto también sucede con los DTD y hojas de estilo, por lo que cada una tiene una propiedad asignada para permitir su ajuste, en el caso de la primera se llama `accessExternalDTD` y en el de la segunda, `accessExternalStylesheet`.

Vale, y ahora, ¿cómo solucionarlo?, no parece complicado, aunque hay varias formas, como por ejemplo añadir el siguiente argumento a la VM `-Djavax.xml.accessExternalSchema=all` o crear un archivo properties con el nombre jaxp en la configuración de la JDK.

Si optas por la vía del properties, debes de saber que la ruta no es la misma en la JDK 1.7 que en la 11, en la 1.7 y 1.8 debe de ir en **${JAVA_HOME}/lib/jaxp.properties**, en cambio, desde la 9 en adelante y al menos hasta la 11 (hasta aquí he mirado), en **${JAVA_HOME}/conf/jaxp.properties**.

Puedes encontrar más información acerca de todo lo que te he contado en la documentación de **XMLConstants**:

- [Java SE 1.7](https://docs.oracle.com/javase/7/docs/api/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_SCHEMA)
- [Java SE 1.8](https://docs.oracle.com/javase/8/docs/api/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_SCHEMA)
- [Java SE 9](https://docs.oracle.com/javase/9/docs/api/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_SCHEMA)
- [Java SE 10](https://docs.oracle.com/javase/10/docs/api/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_SCHEMA)
- [Java SE 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_SCHEMA)

**Comment by xaabi6** [comment]
@JONAGUIPER, ¿habéis podido probar lo último que os comenté?

**Comment by sergeisg** [comment]
Aupa Xabi.
Tras probar las dos soluciones propuestas, tanto el argumento de la VM como la creación del archivo properties, se sigue produciendo exactamente el mismo error que desarrollaba Jon Ander en su último mensaje. 
Un saludo. 

> Hola xabi este es el error: <20-dic-2022 17H17' CET> <Stack trace for message 149004 weblogic.application.ModuleException: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 132; schema_reference: fallo al leer el documento de esquema 'spring-beans-4.3.xsd' porque no se permite el acceso 'http' debido a una restricci�n definida por la propiedad accessExternalSchema. :org.xml.sax.SAXParseException:schema_reference: fallo al leer el documento de esquema 'spring-beans-4.3.xsd' porque no se permite el acceso 'http' debido a una restricci�n definida por la propiedad accessExternalSchema. at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) Truncated. see log file for complete stacktrace
> 
> esto pasa cuando haces publish y no despliega la app lo que obliga a reiniciar el weblogic

**Comment by xaabi6** [comment]
Si lanzáis WebLogic desde Eclipse, probad a meterlo en _eclipse.ini_ a ver si ayuda en algo, además, también definiría ahí la JDK en uso para garantizar que siempre se utilice la misma. Todo esto podéis hacerlo de la siguiente forma:
> -vm
/path/jdk/bin
-vmargs
-Djavax.xml.accessExternalDTD=all
-Djavax.xml.accessExternalSchema=all
-Djavax.xml.accessExternalStylesheet=all

También os recomendaría retocar las variables **SUN_JAVA_HOME** y **DEFAULT_SUN_JAVA_HOME** del dominio para definir una vez más la misma JDK (quizás ya sean correctas).

Otro aspecto importante es la variable de entorno **JAVA_HOME**, aseguraros también de que contenga la referencia a la misma JDK.

Con todo esto, debería de funcionar, al menos en un WebLogic 14 sobre el que me sucedía esto, he sido capaz de eliminar el problema. Ya me contaréis si os da resultado 👍

**Comment by xaabi6** [comment]
@sergeisg y @JONAGUIPER, ¿os sirvieron las últimas pautas?

**Comment by xaabi6** [comment]
Cierro la issue por inactividad. Si necesitáis más ayuda o queréis reportar algún error, ya sabéis dónde encontrarnos 😄
